FormingWorlds/PROTEUS

- .gitmodules
- CouplerMain.py
- init_coupler.opts
- utils/cpl_mapTs.py
- utils/modules_coupler.py
- utils/modules_plot.py
- utils/utils_coupler.py
> Submodule reorder

- INSTALL.md
- TROUBLESHOOTING.md
- utils/modules_coupler.py
- utils/utils_coupler.py
- Additions to INSTALL and TROUBLESHOOTING for Intel and ARM machines
- No dependence on yaml python package
- Updated Coupler Dict append functioning
> Fixes 230506

- .gitignore
- .readthedocs.yaml
- README.md
- docs/Makefile
- docs/make.bat
- docs/source/api.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/usage.rst
- lumache.py
- pyproject.toml
> Docs 230508

- utils/utils_coupler.py
Changes in AEOLUS require calls to `atmos.__init__()` and `RadConvEqm()` in PROTEUS to be updated. See the pull request at https://github.com/FormingWorlds/AEOLUS/pull/25 for details.
> Updated calls to AEOLUS functions to reflect recent changes

- docs/source/installation.rst
Includes instructions on how to install SOCRATES now that it comes packaged with AEOLUS.
Includes info on how to download and install Mors for calculating stellar evolution.
Updates AEOLUS to most recent version.
> Documentation update

- README.md
Update my e-mail address to ETHZ
> Update my e-mail address

- docs/source/usage.rst
- examples/dummy_atmosphere/init_coupler.cfg
- examples/earth_demo/init_coupler.cfg
- input/default.cfg
- input/dummy.cfg
- input/janus_mixed.cfg
- input/jgr_grid.cfg
- input/rce_mixed.cfg
- input/rce_steam.cfg
- plot/cpl_elements.py
- plot/cpl_global.py
- proteus.py
- tools/RunPROTEUS.sh
- tools/SolveVol.ipynb
- utils/constants.py
- utils/coupler.py
- utils/dummy_atmosphere.py
- utils/escape.py
- utils/helper.py
- utils/spider.py
- utils/surface_gases.py
This PR adds basic escape infrastructure, where total elemental mass inventories are updated according to a given escape rate. The escape model and escape rate are specified in the configuration file.
There's also a new break condition, where the model will terminate when the atmosphere mass drops below some small fraction of the initial mass. This represents the volatiles having (almost) entirely escaped. There is a new plot function `plot_elements` to show the mass loss over time.
There's also a stub function for ZEPHYRUS integration, when it's ready.
> Dummy escape module

- .gitignore
- .vscode/settings.json
- docs/installation.md
- pyproject.toml
- src/proteus/atmos_clim/agni.py
- src/proteus/atmos_clim/wrapper_atmosphere.py
- src/proteus/plot/__init__.py
- src/proteus/plot/cpl_atmosphere.py
- src/proteus/plot/cpl_emission.py
- src/proteus/proteus.py
- src/proteus/utils/coupler.py
- src/proteus/utils/plot.py
- src/proteus/utils/spider.py
- tools/GridPROTEUS.py
- New functionality for plotting emission spectrum (closes #154)
- Automatically plots emission at model exit/convergence
- Clarifies developer installation instructions (closes #160)
- Updated gitignore for when modules are cloned inside PROTEUS directory
- Minor improvements to AGNI wrapper, with some refactoring to fit code style
- Checks that SPIDER executable exists before trying to run it
Developer installation instructions probably need further work but this at least explains the difference between the editable and 'normal' install steps.
> Emission spectrum calculation and other minor changes

- CONTRIBUTING.md
- input/hd63433d.toml
- input/l-98-59d.toml
- src/proteus/atmos_clim/agni.py
- src/proteus/atmos_clim/dummy_atmosphere.py
- src/proteus/atmos_clim/wrapper_atmosphere.py
- src/proteus/utils/plot.py
- tools/GetStellarSpectrum.py
- tools/GridPROTEUS.py
- Fixes `rho_obs` key error when running dummy atmosphere
- Added new observing filters
- Restored old script for downloading spectra from MUSCLES. This must have been deleted in the past, but I needed it for getting the L 98-59 spectrum.
> Fixes to dummy atmosphere and other minor changes

- tests/test_config.py
> Do not test example configs

- src/proteus/utils/data.py
Hi all, this PR refactors and optimizes the data download. The OSF interface is delayed until needed and cached to minimize the number of requests.
Addresses #242
> Refactor and optimize data download

- input/aragog.toml
- input/default.toml
- input/dummy.toml
- input/escape.toml
- input/hd63433d.toml
- input/k218b.toml
- input/trappist1c.toml
- pyproject.toml
- src/proteus/atmos_clim/agni.py
- src/proteus/atmos_clim/janus.py
- src/proteus/config/_atmos_clim.py
- src/proteus/utils/plot.py
- tests/integration/dummy.toml
- tests/integration/physical.toml
- tools/grid_proteus.py
- tools/postprocess_grid.jl
This PR adds the option of changing the gas overlap method via the configuration file. Closes #248.
Requires JANUS to be updated to 24.11.05 and AGNI to be on the latest version (as of 5 November).
> Add gas overlap option to config

- docs/installation.md
- src/proteus/interior/aragog.py
* Fixes issue with `core_radius` keyword
* Fixes issue with accessing rheological front as float (not as array)
* Updated documentation.
Still need to add aragog as a pyproject dependency - should be handled in another PR.
> Update aragog wrapper with recent changes

- tests/integration/test_integration_dummy.py
- tests/integration/test_integration_physical.py
As discussed this morning.
Closes #302.
> Neglect checking for CH4 molar abundance

- CITATION.cff
- CONTRIBUTING.md
- README.md
- pyproject.toml
- src/proteus/__init__.py
- src/proteus/plot/cpl_emission.py
- src/proteus/plot/cpl_fluxes_global.py
- src/proteus/plot/cpl_population.py
- src/proteus/proteus.py
- src/proteus/utils/coupler.py
- tests/integration/test_integration_dummy.py
- tests/integration/test_integration_physical.py
* Update bibliographic information
* Print citation info as appropriate (closes #312).
* Fix bug where plots cause crash if model terminates very early
Updates code version to 24.12.17
> Citation info

- docs/installation.md
- docs/tips_kapteyn_cluster.md
- docs/tips_snellius_cluster.md
- docs/usage.md
This pull request includes updates to the installation and usage documentation for different operating systems and cluster environments. The changes aim to provide clearer instructions and better organization for setting up and using PROTEUS.
* [`docs/installation.md`](diffhunk://#diff-8b042e3f94ca5c59a7cd990b950aec0073ea84fe811e7b22be51158d7b180d56L11-R15): Refactored system configuration instructions to separate sections for Mac OS, Linux, and Windows, and added details for remote clusters. Included specific instructions for installing dependencies and setting up the Python environment using `miniforge`. [[1]](diffhunk://#diff-8b042e3f94ca5c59a7cd990b950aec0073ea84fe811e7b22be51158d7b180d56L11-R15) [[2]](diffhunk://#diff-8b042e3f94ca5c59a7cd990b950aec0073ea84fe811e7b22be51158d7b180d56L20 …
> Update docs ext

- CONTRIBUTING.md
- README.md
- docs/installation.md
- docs/tips_kapteyn_cluster.md
- docs/tips_snellius_cluster.md
- docs/usage.md
This pull request includes updates to documentation files to enhance clarity and provide additional guidance for users. The most important changes include improvements to installation instructions, reorganization of sections, and updates to contributor information.
Documentation improvements:
* [`docs/installation.md`](diffhunk://#diff-8b042e3f94ca5c59a7cd990b950aec0073ea84fe811e7b22be51158d7b180d56L11-R15): Expanded system configuration instructions for Mac OS, Linux, and Windows, and added detailed steps for setting up a Python environment and creating environment variables. [[1]](diffhunk://#diff-8b042e3f94ca5c59a7cd990b950aec0073ea84fe811e7b22be51158d7b180d56L11-R15) [[2]](diffhunk://#diff-8b042e3f94ca5c59a7cd990b950aec0073ea84fe811e7b22be51158d7b180d56L20-R70) …
> Update documentation for Kapteyn cluster usage

- tools/grid_proteus.py
This PR adds a way to generate a slurm batch file for `grid_proteus.py`.
Submit using: `sbatch proteus_slurm_array.sh`
Addresses #355
> Generate slurm config from grid_proteus

- .github/workflows/tests.yaml
- input/planets/l9859d.toml
- pyproject.toml
- src/proteus/observe/platon.py
- src/proteus/proteus.py
- src/proteus/utils/coupler.py
- src/proteus/utils/data.py
- tools/grid_proteus.py
* Limit platon temperature profile to valid range. Closes #392 
* Change helpfile.csv precision to %.10e from %.8e, to avoid roundoff errors in Time column
* Write helpfile on final iteration before synthetic observations, so that they use the correct data.
* Re-attempt download from OSF up to three times. Closes #206.
Resolves issue #395 by manually adding libssl to the Ubuntu deps, and forcing AGNI to use OpenSSL v3.0 rather than v3.5 (changes made in the AGNI repo).
> Limit platon temperature range, and a mitigation for data-download failures

- src/proteus/atmos_clim/common.py
- src/proteus/plot/__init__.py
- src/proteus/plot/cpl_visual.py
- src/proteus/utils/archive.py
- src/proteus/utils/coupler.py
- src/proteus/utils/visual.py
This PR introduces a new plot, which is generated automatically at the end of each simulation. See example below. The planet's atmosphere is plotted as a series of concentric circles, with the colour of each circle set by the radiation fluxes calculated during the simulation. These fluxes are mapped to colours using [CIE colour matching functions](https://en.wikipedia.org/wiki/CIE_1931_color_space?useskin=vector) with some tweaks. Closes #404.
It also includes the star in the background, scaled based on its distance and relative size. The inset shows the emission spectrum calculated by SOCRATES.
This is useful for visualising how the planet cools and contracts over time. These plots could be used in presentations, proposals, etc.
I have externally made a notebook which generates frames of …
> New plot to visualise planet evolution

- docs/troubleshooting.md
- mkdocs.yml
- pyproject.toml
- src/proteus/proteus.py
- src/proteus/utils/coupler.py
Ensures that a user is using up-to-date versions of modules. Raises an error if one of the modules is out of date. Adds documentation explaining what to do if this is the case. Closes #398.
Also tidied up docs page: Troubleshooting.md
> Validate module versions

- docs/installation.md
Added blank lines, the two lists should not collapse now.
> Uncollapse requirements and steps lists
